version: "3.7"

services: 
  db:
    image: bh0na/gnuhealth-postgres
    container_name: gnuhealth-postgres
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=gnuhealth
      - POSTGRES_PASSWORD=jkUbZGvFNeugk
      - POSTGRES_DB=gnuhealth
    networks: 
      - gnuhealth    

  tryton:
    image: bh0na/tryton-server-gnuhealth:dev
    # build: 
    #   context: ./tryton-server-gnuhealth
    #   dockerfile: Dockerfile
    container_name: tryton-server-gnuhealth
    volumes:
      - ./tryton-server-gnuhealth/gnuhealth-latest:/home/gnuhealth/gnuhealth-latest
      - ./tryton-server-gnuhealth/modules:/home/gnuhealth/gnuhealth/tryton/server/modules
    environment:
      - DB_USER=gnuhealth
      - DB_PASSWORD=jkUbZGvFNeugk
      - DB_HOSTNAME=db
      - DB_PORT=5432
    depends_on: 
      - db
    ports:
      - "8000:8000"
    networks: 
      - gnuhealth

networks: 
  gnuhealth: